### ISSUE TITLE
ReadMe Instructions Mistake in Go Version Determination

### ISSUE THREAD

**Issue by emendir** [ipfs/go-ipfs-example-plugin#31]
First of all, thanks for the work on making this example plugin usable again!

There is an issue, however, in the instructions in the ReadMe, where it says:

> You need to be using the same Go version to compile Kubo and the plugin. Upstream releases of Kubo use [whatever it says here](https://github.com/ipfs/distributions/blob/master/.tool-versions#L2) (v0.19.10) at the time of writing.

The provided URL doesn't always provide the correct version. On the 6th of August 2023 I tried following the instructions with the latest version of kubo (0.21.0). At that time the link in the instructions https://github.com/ipfs/distributions/blob/master/.tool-versions#L2 said `golang 1.19.11`, which resulted in errors when running the plugin. When running kubo in the terminal with `ipfs daemon`, I noticed in the console output it said `Golang version: go1.19.10`, so I reinstalled go with that version and then the plugin worked.

**Comment by hsanjuan** [comment]
Yes, much better to use `ipfs version --all` to check that, which includes the Go version. Mind PRing this?
